name: $name
version: $version
main: de.leghast.holography.Holography
api-version: "$apiVersion"
authors: [GhastCraftHD]
description: $description

commands:
  hologram:
    aliases: holo
    description: The main command from Holography
    permission: holography.use

permissions:
  holography.use:
    default: op
    description: The permissions that lets you use Holography
